### ISSUE TITLE
Losing the third resource

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#39]
In the most recent run, the log shows 3 resources migrated for node 4537, but only two are visible in ckan (the zip is dropped not appearing): https://test-data.hdx.rwlabs.org/dataset/afghanistan-population-statistics#

Log entries:

```
2015-07-10T13:51:51+0200 | dataset | START | True | 4537 | None | https://www.humanitarianresponse.info/en/api/v1.0/datasets/4537 | None | None | None | None | None
2015-07-10T13:51:52+0200 | dataset | get | True | 4537 | https://www.humanitarianresponse.info/en/operations/afghanistan/dataset/afghanistan-population-statistics | https://www.humanitarianresponse.info/en/api/v1.0/datasets/4537 | None | None | None | None | None
2015-07-10T13:51:52+0200 | dataset | format | True | 4537 | https://www.humanitarianresponse.info/en/operations/afghanistan/dataset/afghanistan-population-statistics | https://www.humanitarianresponse.info/en/api/v1.0/datasets/4537 | None | Afghanistan - Population Statistics | None | None | None
2015-07-10T13:51:59+0200 | dataset | update | True | 4537 | https://www.humanitarianresponse.info/en/operations/afghanistan/dataset/afghanistan-population-statistics | https://www.humanitarianresponse.info/en/api/v1.0/datasets/4537 | 4c58fa87-3259-4cc8-a35c-48489cafb773 | Afghanistan - Population Statistics | None | https://test-data.hdx.rwlabs.org/dataset/afghanistan-population-statistics | https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=afghanistan-population-statistics
2015-07-10T13:51:59+0200 | resource | format | True | 51842 | https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/datasets/AFG_CSO_POP_DISTRICT_2014_2015_OCHA_201409Sep08.xlsx | None | AFG_CSO_POP_DISTRICT_2014_2015_OCHA_201409Sep08.xlsx | None | afghanistan-population-statistics | None | https://test-data.hdx.rwlabs.org/api/3/action/resource_show?id=AFG_CSO_POP_DISTRICT_2014_2015_OCHA_201409Sep08.xlsx
2015-07-10T13:52:00+0200 | resource | get | True | 51842 | https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/datasets/AFG_CSO_POP_DISTRICT_2014_2015_OCHA_201409Sep08.xlsx | None | AFG_CSO_POP_DISTRICT_2014_2015_OCHA_201409Sep08.xlsx | None | afghanistan-population-statistics | None | https://test-data.hdx.rwlabs.org/api/3/action/resource_show?id=AFG_CSO_POP_DISTRICT_2014_2015_OCHA_201409Sep08.xlsx
2015-07-10T13:52:22+0200 | resource | create | True | 51842 | https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/datasets/AFG_CSO_POP_DISTRICT_2014_2015_OCHA_201409Sep08.xlsx | None | AFG_CSO_POP_DISTRICT_2014_2015_OCHA_201409Sep08.xlsx | None | afghanistan-population-statistics | None | https://test-data.hdx.rwlabs.org/api/3/action/resource_show?id=AFG_CSO_POP_DISTRICT_2014_2015_OCHA_201409Sep08.xlsx
2015-07-10T13:52:22+0200 | resource | format | True | 3860 | https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/AFG_CSO_POP_DISTRICT_2013_2014_OCHA_201307JUL31.xlsx | None | AFG_CSO_POP_DISTRICT_2013_2014_OCHA_201307JUL31.xlsx | None | afghanistan-population-statistics | None | https://test-data.hdx.rwlabs.org/api/3/action/resource_show?id=AFG_CSO_POP_DISTRICT_2013_2014_OCHA_201307JUL31.xlsx
2015-07-10T13:52:24+0200 | resource | get | True | 3860 | https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/AFG_CSO_POP_DISTRICT_2013_2014_OCHA_201307JUL31.xlsx | None | AFG_CSO_POP_DISTRICT_2013_2014_OCHA_201307JUL31.xlsx | None | afghanistan-population-statistics | None | https://test-data.hdx.rwlabs.org/api/3/action/resource_show?id=AFG_CSO_POP_DISTRICT_2013_2014_OCHA_201307JUL31.xlsx
2015-07-10T13:52:32+0200 | resource | create | True | 3860 | https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/AFG_CSO_POP_DISTRICT_2013_2014_OCHA_201307JUL31.xlsx | None | AFG_CSO_POP_DISTRICT_2013_2014_OCHA_201307JUL31.xlsx | None | afghanistan-population-statistics | None | https://test-data.hdx.rwlabs.org/api/3/action/resource_show?id=AFG_CSO_POP_DISTRICT_2013_2014_OCHA_201307JUL31.xlsx
2015-07-10T13:52:32+0200 | resource | format | True | 3861 | https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/CSO%20Estimated%20Population%20of%20Afghanistan%202013-14%20Report.zip | None | CSO Estimated Population of Afghanistan 2013-14 Report.zip | None | afghanistan-population-statistics | None | https://test-data.hdx.rwlabs.org/api/3/action/resource_show?id=CSO Estimated Population of Afghanistan 2013-14 Report.zip
2015-07-10T13:52:41+0200 | resource | get | True | 3861 | https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/CSO%20Estimated%20Population%20of%20Afghanistan%202013-14%20Report.zip | None | CSO Estimated Population of Afghanistan 2013-14 Report.zip | None | afghanistan-population-statistics | None | https://test-data.hdx.rwlabs.org/api/3/action/resource_show?id=CSO Estimated Population of Afghanistan 2013-14 Report.zip
2015-07-10T13:53:54+0200 | resource | create | True | 3861 | https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/CSO%20Estimated%20Population%20of%20Afghanistan%202013-14%20Report.zip | None | CSO Estimated Population of Afghanistan 2013-14 Report.zip | None | afghanistan-population-statistics | None | https://test-data.hdx.rwlabs.org/api/3/action/resource_show?id=CSO Estimated Population of Afghanistan 2013-14 Report.zip
zip
2015-07-10T13:54:00+0200 | dataset | update | True | 4537 | https://www.humanitarianresponse.info/en/operations/afghanistan/dataset/afghanistan-population-statistics | https://www.humanitarianresponse.info/en/api/v1.0/datasets/4537 | 4c58fa87-3259-4cc8-a35c-48489cafb773 | Afghanistan - Population Statistics | None | https://test-data.hdx.rwlabs.org/dataset/afghanistan-population-statistics | https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=afghanistan-population-statistics
2015-07-10T13:54:00+0200 | dataset | COMPLETE | True | 4537 | https://www.humanitarianresponse.info/en/operations/afghanistan/dataset/afghanistan-population-statistics | https://www.humanitarianresponse.info/en/api/v1.0/datasets/4537 | 4c58fa87-3259-4cc8-a35c-48489cafb773 | Afghanistan - Population Statistics | None | https://test-data.hdx.rwlabs.org/dataset/afghanistan-population-statistics | https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=afghanistan-population-statistics
```

**Comment by teodorescuserban** [comment]
please test again. I was runnning a test on the same exact dataset.
on each dataset update, if the resources' metadata are not included in the dataset update call, they will just get lost.

**Comment by cjhendrix** [comment]
I can't successfully migrate anything now.  I'm getting NOMIGRATE-INCOMPLETE.  The log is below and the console is prting this error:

```
Trying to get resources/mli_admin_shp.zip
Uploading resource resources/mli_admin_shp.zip
FAILED.
{"help": "http://test-data.hdx.rwlabs.org/api/3/action/help_show?name=resource_create", "success": false, "error": {"url": ["Missing value"], "__type": "Validation Error"}}
Error occured when create : False
```

  Here's my latest test run log:

2015-07-14T16:03:13+0200 | dataset | START | True | 22243 | None | https://www.humanitarianresponse.info/en/api/v1.0/datasets/22243 | None | None | None | None | None
2015-07-14T16:03:14+0200 | dataset | get | True | 22243 | https://www.humanitarianresponse.info/en/operations/afghanistan/dataset/afghanistan-admin-level-1-boundaries | https://www.humanitarianresponse.info/en/api/v1.0/datasets/22243 | None | None | None | None | None
2015-07-14T16:03:14+0200 | dataset | format | True | 22243 | https://www.humanitarianresponse.info/en/operations/afghanistan/dataset/afghanistan-admin-level-1-boundaries | https://www.humanitarianresponse.info/en/api/v1.0/datasets/22243 | None | Afghanistan - Admin Level 1 Boundaries | None | None | None
2015-07-14T16:03:18+0200 | dataset | create | True | 22243 | https://www.humanitarianresponse.info/en/operations/afghanistan/dataset/afghanistan-admin-level-1-boundaries | https://www.humanitarianresponse.info/en/api/v1.0/datasets/22243 | 635f15d9-40f3-4d15-b8f2-4611253028bc | Afghanistan - Admin Level 1 Boundaries | None | https://test-data.hdx.rwlabs.org/dataset/afghanistan-admin-level-1-boundaries | https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=afghanistan-admin-level-1-boundaries
2015-07-14T16:03:18+0200 | resource | format | True | 18900 | https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/datasets/afg_admbnd_reg_UNAMA.zip | None | afg_admbnd_reg_UNAMA.zip | None | afghanistan-admin-level-1-boundaries | None | https://test-data.hdx.rwlabs.org/api/3/action/resource_show?id=afg_admbnd_reg_UNAMA.zip
2015-07-14T16:03:20+0200 | resource | get | True | 18900 | https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/datasets/afg_admbnd_reg_UNAMA.zip | None | afg_admbnd_reg_UNAMA.zip | None | afghanistan-admin-level-1-boundaries | None | https://test-data.hdx.rwlabs.org/api/3/action/resource_show?id=afg_admbnd_reg_UNAMA.zip
2015-07-14T16:03:21+0200 | dataset | NOMIGRATE-INCOMPLETE | False | 22243 | https://www.humanitarianresponse.info/en/operations/afghanistan/dataset/afghanistan-admin-level-1-boundaries | https://www.humanitarianresponse.info/en/api/v1.0/datasets/22243 | 635f15d9-40f3-4d15-b8f2-4611253028bc | Afghanistan - Admin Level 1 Boundaries | None | https://test-data.hdx.rwlabs.org/dataset/afghanistan-admin-level-1-boundaries | https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=afghanistan-admin-level-1-boundaries
2015-07-14T16:03:21+0200 | dataset | START | True | 4246 | None | https://www.humanitarianresponse.info/en/api/v1.0/datasets/4246 | None | None | None | None | None
2015-07-14T16:03:22+0200 | dataset | get | True | 4246 | https://www.humanitarianresponse.info/en/operations/yemen/dataset/yemen-admin-level-1-boundaries-admin-level-2-boundaries | https://www.humanitarianresponse.info/en/api/v1.0/datasets/4246 | None | None | None | None | None
2015-07-14T16:03:22+0200 | dataset | format | True | 4246 | https://www.humanitarianresponse.info/en/operations/yemen/dataset/yemen-admin-level-1-boundaries-admin-level-2-boundaries | https://www.humanitarianresponse.info/en/api/v1.0/datasets/4246 | None | Yemen - Admin Boundaries, Settlements | None | None | None
2015-07-14T16:03:24+0200 | dataset | create | True | 4246 | https://www.humanitarianresponse.info/en/operations/yemen/dataset/yemen-admin-level-1-boundaries-admin-level-2-boundaries | https://www.humanitarianresponse.info/en/api/v1.0/datasets/4246 | 24730302-590d-4539-9914-a6ae37c5f490 | Yemen - Admin Boundaries, Settlements | None | https://test-data.hdx.rwlabs.org/dataset/yemen-admin-boundaries-settlements | https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=yemen-admin-boundaries-settlements
2015-07-14T16:03:24+0200 | resource | format | True | 3774 | https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/yemen_p-codes_27032013.xlsx | None | yemen_p-codes_27032013.xlsx | None | yemen-admin-boundaries-settlements | None | https://test-data.hdx.rwlabs.org/api/3/action/resource_show?id=yemen_p-codes_27032013.xlsx
2015-07-14T16:03:33+0200 | resource | get | True | 3774 | https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/yemen_p-codes_27032013.xlsx | None | yemen_p-codes_27032013.xlsx | None | yemen-admin-boundaries-settlements | None | https://test-data.hdx.rwlabs.org/api/3/action/resource_show?id=yemen_p-codes_27032013.xlsx
2015-07-14T16:03:34+0200 | dataset | NOMIGRATE-INCOMPLETE | False | 4246 | https://www.humanitarianresponse.info/en/operations/yemen/dataset/yemen-admin-level-1-boundaries-admin-level-2-boundaries | https://www.humanitarianresponse.info/en/api/v1.0/datasets/4246 | 24730302-590d-4539-9914-a6ae37c5f490 | Yemen - Admin Boundaries, Settlements | None | https://test-data.hdx.rwlabs.org/dataset/yemen-admin-boundaries-settlements | https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=yemen-admin-boundaries-settlements
2015-07-14T16:03:34+0200 | dataset | START | True | 4537 | None | https://www.humanitarianresponse.info/en/api/v1.0/datasets/4537 | None | None | None | None | None
2015-07-14T16:03:34+0200 | dataset | get | True | 4537 | https://www.humanitarianresponse.info/en/operations/afghanistan/dataset/afghanistan-population-statistics | https://www.humanitarianresponse.info/en/api/v1.0/datasets/4537 | None | None | None | None | None
2015-07-14T16:03:34+0200 | dataset | format | True | 4537 | https://www.humanitarianresponse.info/en/operations/afghanistan/dataset/afghanistan-population-statistics | https://www.humanitarianresponse.info/en/api/v1.0/datasets/4537 | None | Afghanistan - Population Statistics | None | None | None
2015-07-14T16:03:41+0200 | dataset | create | True | 4537 | https://www.humanitarianresponse.info/en/operations/afghanistan/dataset/afghanistan-population-statistics | https://www.humanitarianresponse.info/en/api/v1.0/datasets/4537 | eac61c6f-4e3b-4e19-9f4f-0e8556d1f793 | Afghanistan - Population Statistics | None | https://test-data.hdx.rwlabs.org/dataset/afghanistan-population-statistics | https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=afghanistan-population-statistics
2015-07-14T16:03:41+0200 | resource | format | True | 51842 | https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/datasets/AFG_CSO_POP_DISTRICT_2014_2015_OCHA_201409Sep08.xlsx | None | AFG_CSO_POP_DISTRICT_2014_2015_OCHA_201409Sep08.xlsx | None | afghanistan-population-statistics | None | https://test-data.hdx.rwlabs.org/api/3/action/resource_show?id=AFG_CSO_POP_DISTRICT_2014_2015_OCHA_201409Sep08.xlsx
2015-07-14T16:03:42+0200 | resource | get | True | 51842 | https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/datasets/AFG_CSO_POP_DISTRICT_2014_2015_OCHA_201409Sep08.xlsx | None | AFG_CSO_POP_DISTRICT_2014_2015_OCHA_201409Sep08.xlsx | None | afghanistan-population-statistics | None | https://test-data.hdx.rwlabs.org/api/3/action/resource_show?id=AFG_CSO_POP_DISTRICT_2014_2015_OCHA_201409Sep08.xlsx
2015-07-14T16:03:43+0200 | dataset | NOMIGRATE-INCOMPLETE | False | 4537 | https://www.humanitarianresponse.info/en/operations/afghanistan/dataset/afghanistan-population-statistics | https://www.humanitarianresponse.info/en/api/v1.0/datasets/4537 | eac61c6f-4e3b-4e19-9f4f-0e8556d1f793 | Afghanistan - Population Statistics | None | https://test-data.hdx.rwlabs.org/dataset/afghanistan-population-statistics | https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=afghanistan-population-statistics
2015-07-14T16:03:43+0200 | dataset | START | True | 104565 | None | https://www.humanitarianresponse.info/en/api/v1.0/datasets/104565 | None | None | None | None | None
2015-07-14T16:03:44+0200 | dataset | get | True | 104565 | https://www.humanitarianresponse.info/en/applications/data/dataset/mali-admin-level-0-international-boundaries | https://www.humanitarianresponse.info/en/api/v1.0/datasets/104565 | None | None | None | None | None
2015-07-14T16:03:44+0200 | dataset | format | True | 104565 | https://www.humanitarianresponse.info/en/applications/data/dataset/mali-admin-level-0-international-boundaries | https://www.humanitarianresponse.info/en/api/v1.0/datasets/104565 | None | Mali - Admin Boundaries | None | None | None
2015-07-14T16:03:45+0200 | dataset | create | True | 104565 | https://www.humanitarianresponse.info/en/applications/data/dataset/mali-admin-level-0-international-boundaries | https://www.humanitarianresponse.info/en/api/v1.0/datasets/104565 | efe38a63-14a2-45bb-8ae6-cf61f10bac5e | Mali - Admin Boundaries | None | https://test-data.hdx.rwlabs.org/dataset/mali-admin-boundaries | https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=mali-admin-boundaries
2015-07-14T16:03:45+0200 | resource | format | True | 97946 | https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/datasets/mli_admin_shp_0.zip | None | mli_admin_shp.zip | None | mali-admin-boundaries | None | https://test-data.hdx.rwlabs.org/api/3/action/resource_show?id=mli_admin_shp.zip
2015-07-14T16:03:49+0200 | resource | get | True | 97946 | https://www.humanitarianresponse.info/sites/www.humanitarianresponse.info/files/datasets/mli_admin_shp_0.zip | None | mli_admin_shp.zip | None | mali-admin-boundaries | None | https://test-data.hdx.rwlabs.org/api/3/action/resource_show?id=mli_admin_shp.zip
2015-07-14T16:03:51+0200 | dataset | NOMIGRATE-INCOMPLETE | False | 104565 | https://www.humanitarianresponse.info/en/applications/data/dataset/mali-admin-level-0-international-boundaries | https://www.humanitarianresponse.info/en/api/v1.0/datasets/104565 | efe38a63-14a2-45bb-8ae6-cf61f10bac5e | Mali - Admin Boundaries | None | https://test-data.hdx.rwlabs.org/dataset/mali-admin-boundaries | https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=mali-admin-boundaries

**Comment by teodorescuserban** [comment]
This is related to test-data upgrade to ckan 2.3 (I told you few hours ago on call with @danmihaila I solved the resource_create issue, that was related with new ckan being really keen to provide a url field even on a resource upload).

It should have been fixed now.
Let's also try (and fail) to replicate tomorrow on BM.

**Comment by cjhendrix** [comment]
Still happening.   http://feature-data.hdx.rwlabs.org/dataset/afghanistan-population-statistics#

**Comment by teodorescuserban** [comment]
Please try again on the new test stack, @cjhendrix :(

**Comment by teodorescuserban** [comment]
This keeps working fine on the new test stack.
Mind if we try again tomorrow?

**Comment by teodorescuserban** [comment]
Closing.
Reopen if you see it again.
