### ISSUE TITLE
After license issue is resolved, edit the URL in the default Terms of Use text

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#43]
When gospawn detects the default terms of use text, it maintains the URL to the HR.info terms of use.  However, after https://github.com/OCHA-DAP/hdx-ckan/issues/3055 is resolved, we can change the URL to be the HDX url for this terms of use file.

**Comment by teodorescuserban** [comment]
I am a bit confused (again) about "License" and "Terms of Use"

Please see this 3 examples:
1. Example 1 - non-default `terms_of_use` field in HR dataset
   https://www.humanitarianresponse.info/en/api/v1.0/datasets/4537
   http://test-data.hdx.rwlabs.org/dataset/afghanistan-population-statistics
2. Example 2 - empty `terms_of_use` field in HR dataset
   https://www.humanitarianresponse.info/en/api/v1.0/datasets/4130
   http://test-data.hdx.rwlabs.org/dataset/jordan-other
3. Example 3 - default `terms_of_use` field in HR dataset
   https://www.humanitarianresponse.info/en/api/v1.0/datasets/4246
   http://test-data.hdx.rwlabs.org/dataset/yemen-administrative-boundaries-settlements

Please check for all three examples the HDX dataset metadata on `License` field for the following:

a. target url for `Other` anchor.

b. text below ``Other` anchor.

c. target url for the anchor below `Other` (where applicable)

and write down on this issue what is the desired outcome.

Also please give me an option if some HR.info dataset does not have the `terms_of_use` field at all (most likely I would apply the same solution as for a dataset with an empty `terms_of_use` field).

**Comment by teodorescuserban** [comment]
tagging @cjhendrix

**Comment by cjhendrix** [comment]
## **Summary**:  
1. If there is non-default text for this field we migrate the text.
2. If there is default text (in any language) we use our own (very similar) default text.
3. If terms_of_use is blank or missing, same as number 2 above.

## **Specifics**:

1) Example 1 - non-default `terms_of_use` field in HR dataset
https://www.humanitarianresponse.info/en/api/v1.0/datasets/4537
http://test-data.hdx.rwlabs.org/dataset/afghanistan-population-statistics

a) does not change
b) Should be 
`This dataset should be used in accordance with the "Estimated Population of Afghanistan 2013 / 14" report prepared by the Islamic Republic of Afghanistan CSO.`
c) No anchor

2) Example 2 - empty `terms_of_use` field in HR dataset
https://www.humanitarianresponse.info/en/api/v1.0/datasets/4130
http://test-data.hdx.rwlabs.org/dataset/jordan-other

a) does not change
b) use the default COD terms of use string: 
`See this [terms of use](http://data.hdx.rwlabs.org/about/license/legacy_hrinfo). This does not replace any terms of use information provided with the dataset.`
c) http://data.hdx.rwlabs.org/about/license/legacy_hrinfo

3) Example 3 - default `terms_of_use` field in HR dataset
https://www.humanitarianresponse.info/en/api/v1.0/datasets/4246
http://test-data.hdx.rwlabs.org/dataset/yemen-administrative-boundaries-settlements

a) does not change
b) use the default COD terms of use string: 
`See this [terms of use](http://data.hdx.rwlabs.org/about/license/legacy_hrinfo). This does not replace any terms of use information provided with the dataset.`
c) http://data.hdx.rwlabs.org/about/license/legacy_hrinfo

4) Example 4 - default **french** `terms_of_use` field in HR dataset
https://www.humanitarianresponse.info/en/api/v1.0/datasets/90424

a) does not change
b) use the default COD terms of use string (which is in EN): 
`See this [terms of use](http://data.hdx.rwlabs.org/about/license/legacy_hrinfo). This does not replace any terms of use information provided with the dataset.`
c) http://data.hdx.rwlabs.org/about/license/legacy_hrinfo

5) Example 5 - default **spanish** `terms_of_use` field in HR dataset
Have not yet found an example of this.  Will add here when I do.  It will be handled the same as number 4 above.

**Comment by cjhendrix** [comment]
On your last question.  If terms_of_use is missing from the API, yes, apply the same  result as for number 2 above.

**Comment by teodorescuserban** [comment]
How do I infer I should put the text in french, @cjhendrix ?
Only by comparing the terms_of_use strings? 
In the Example 4 above, the language is english all over but for the terms_of_use.

**Comment by teodorescuserban** [comment]
Fixed.

Please see example 1, 2, 3, 4 here:
http://test-data.hdx.rwlabs.org/dataset/afghanistan-population-statistics
http://test-data.hdx.rwlabs.org/dataset/jordan-other
http://test-data.hdx.rwlabs.org/dataset/yemen-administrative-boundaries-settlements
http://test-data.hdx.rwlabs.org/dataset/central-african-republic-elevation-model

**Comment by cjhendrix** [comment]
Looks like the yemen one had been modified so it didn't match the default string, right?  We will have to catch those manually. 

Also, I've been running tests with the latest code from bitbucket and I still see the old default text.  Maybe you haven't pushed?
